[package]
name = "audio-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-player = { path = "../audio-player"}
tempfile = "3.3.0"
