[package]
name = "audio-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-player = { path = "../audio-player"}
minifb = "0.23.0" # window mainly for PoC
plotters = "0.3.4" # charts
